version: 2

references:

working_directory: &working_directory
  ~/project

docker-ci: &docker-ci
  docker:
    - image: 923133779345.dkr.ecr.us-east-1.amazonaws.com/k8s-deployer:0.0.1
      aws_auth:
  working_directory: *working_directory

jobs:

  build-push:
    <<: *docker-ci
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make docker-push

  deploy:
    <<: *docker-ci
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make k8s-auth
      - run:
          name: Get AWS secrets
          command: scripts/moda-secrets
          environment:
            OUTPUT_DIR: helm/start-bundle
      - run: make helm-deploy

workflows:
  version: 2
  build-push-deploy:
    jobs:
      - build-push:
          context: production-rds

      - hold-deploy:
          type: approval
          requires:
            - build-push

      - deploy:
          context: production-rds
          requires:
            - hold-deploy
          environment:
            EKS_CLUSTER_NAME: poc-eks-cluster
            AWS_SECRET_NAMES: sandbox/starter-bundle
